In [146]:
import sys
sys.path.append('../src/')

import numpy as np
from src.utils import get_fullname_vectors, get_initial_weights

In [147]:
fullname = np.array(['Іванків', 'Ростислав', 'Богданович'])
print(fullname)
print(f'Max len: {max(*map(len, fullname))}')
print(f'Max word: {max(fullname, key=len)}')

['Іванків' 'Ростислав' 'Богданович']
Max len: 10
Max word: Богданович


In [148]:
fullname_vectors = np.array(get_fullname_vectors(fullname))
print(fullname_vectors)

[[0 1 0 0 1 0 1 0 1 0]
 [0 1 0 0 1 0 1 1 1 0]
 [0 1 0 0 1 0 0 0 1 0]
 [0 1 0 0 1 0 0 1 0 0]
 [1 0 1 0 0 1 0 0 0 0]
 [0 1 0 0 1 0 0 0 0 0]
 [0 1 0 0 1 0 1 1 0 0]
 [1 0 1 0 0 1 0 1 0 0]
 [1 0 1 0 0 1 1 0 0 0]]


In [149]:
weights = np.array(get_initial_weights())
print(weights)

[[0.1 0.2 0.3]
 [0.1 0.2 0.3]
 [0.1 0.2 0.3]
 [0.1 0.5 0.3]
 [0.8 0.7 0.3]
 [0.9 0.2 0.2]
 [0.  0.6 0.6]
 [0.2 0.6 0.5]
 [0.3 0.3 0.3]
 [0.1 0.2 1. ]]


In [150]:
num_of_vectors, vectors_dimension = fullname_vectors.shape
num_of_classes = 3
R = 0
LR = 0.6 # learning rate
threshold = 0.0005

assert (vectors_dimension, num_of_classes) == weights.shape
assert np.all((0 <= weights) & (weights <= 1))

In [151]:
def end_condition(current_weights, previous_weights):
    return np.all(np.abs(current_weights - previous_weights) <= threshold)

def change_weights(_weights, s_i):
    return _weights + (LR * (s_i - _weights))

def get_winner_index(_weights):
    return np.argmin(np.sum((_weights.T - v) ** 2, axis=1))

In [152]:
weights = np.array([[0.7, 0.6],
                    [0.4, 0.1],
                    [0.5, 0.5],
                    [0.2, 0.9]])

fullname_vectors = np.array([[0, 0, 0, 1],
                             [0, 0, 1, 1],
                             [1, 0, 0, 0],
                             [1, 1, 0, 0]])

flag = True
while flag:
    for v in fullname_vectors:
        winner_index = get_winner_index(weights)
        w_before = weights.copy()
        weights[:,winner_index] = change_weights(weights[:,winner_index], v)
        # print(w_before[:,winner_index], '->', weights[:,winner_index])
        if end_condition(weights, w_before):
            flag = False
    LR = LR * 0.5

print(weights)

[[0.98748012 0.02503977]
 [0.57832124 0.00417329]
 [0.02086647 0.58249453]
 [0.00834659 0.99582671]]
